<?php
/**
 * @copyright Copyright © 2020 CreenSight. All rights reserved.
 * @author CreenSight Development Team <magento@creensight.com>
 */

if ($block->allowDeleteAccount()) : ?>
    <div class="cs-gdpr-delete-customer-account col-cs cs-12 cs-xs-12">
        <fieldset class="fieldset info cs-gdpr-delete-account">
            <legend class="legend">
                <span><?= /** @noEscape */ __('Delete Account') ?></span>
            </legend><br>
            <div class="gdpr-delete-message col-cs cs-12 cs-xs-12">
                <?= /** @noEscape */ __($block->getDeleteAccountMessage())?>
            </div>

            <?= /** @noEscape */ $block->getChildHtml('form_additional_info') ?>

            <div class="actions-toolbar col-cs cs-12 cs-xs-12">
                <div class="primary">
                    <button type="submit" class="action save primary action-delete" role="delete-account" data-address="" title="<?= /** @noEscape */ __('Delete your account') ?>">
                        <span><?= /** @noEscape */ __('Delete your account') ?></span>
                    </button>
                </div>
            </div>
        </fieldset>
    </div>
    <script type="text/x-magento-init">
        {
            ".page-main": {
                "address": {
                    "deleteAddress": "button[role='delete-account']",
                    "deleteUrlPrefix": "<?= /** @noEscape */ $block->escapeUrl(rtrim($block->getDeleteAccountUrl(), '/')) ?>",
                    "deleteConfirmMessage": "<?= /** @noEscape */ __('Are you sure you want to delete your account?') ?>",
                    "extraData": <?= /** @noEscape */ $block->getExtraData() ?>
                }
            }
        }
    </script>
<?php endif; ?>
